In [1]:
try:
    %tensorflow_version 2.x
    COLAB = True
    print("Note: using Google CoLab")
except:
    print("Note: not using Google CoLab")
    COLAB = False

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
Note: using Google CoLab


In [2]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

In [3]:
df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

In [7]:
df.head()

sepal_l  sepal_w  petal_l  petal_w      species
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [5]:
# Convert to numpy - Classification
x = df[['sepal_l', 'sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Classification
species = dummies.columns
y = dummies.values

In [6]:
y.shape

(150, 3)

In [8]:
# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1
model.add(Dense(25, activation='relu')) # Hidden 2
model.add(Dense(y.shape[1],activation='softmax')) # Output

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
5/5 - 1s - loss: 1.2413 - 629ms/epoch - 126ms/step
Epoch 2/100
5/5 - 0s - loss: 1.1056 - 13ms/epoch - 3ms/step
Epoch 3/100
5/5 - 0s - loss: 1.0334 - 14ms/epoch - 3ms/step
Epoch 4/100
5/5 - 0s - loss: 0.9687 - 12ms/epoch - 2ms/step
Epoch 5/100
5/5 - 0s - loss: 0.9074 - 13ms/epoch - 3ms/step
Epoch 6/100
5/5 - 0s - loss: 0.8564 - 13ms/epoch - 3ms/step
Epoch 7/100
5/5 - 0s - loss: 0.8099 - 13ms/epoch - 3ms/step
Epoch 8/100
5/5 - 0s - loss: 0.7712 - 11ms/epoch - 2ms/step
Epoch 9/100
5/5 - 0s - loss: 0.7228 - 13ms/epoch - 3ms/step
Epoch 10/100
5/5 - 0s - loss: 0.6897 - 12ms/epoch - 2ms/step
Epoch 11/100
5/5 - 0s - loss: 0.6548 - 11ms/epoch - 2ms/step
Epoch 12/100
5/5 - 0s - loss: 0.6237 - 10ms/epoch - 2ms/step
Epoch 13/100
5/5 - 0s - loss: 0.5946 - 11ms/epoch - 2ms/step
Epoch 14/100
5/5 - 0s - loss: 0.5675 - 12ms/epoch - 2ms/step
Epoch 15/100
5/5 - 0s - loss: 0.5413 - 11ms/epoch - 2ms/step
Epoch 16/100
5/5 - 0s - loss: 0.5223 - 15ms/epoch - 3ms/step
Epoch 17/100
5/5 - 0s - loss: 

In [11]:
# Print out number of species found:
print(species)

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')


In [14]:
pred = model.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])
print(species[predict_classes[0:10]])

Shape: (150, 3)
[[9.9584866e-01 4.1513778e-03 1.6343831e-09]
 [9.8965454e-01 1.0345420e-02 1.6090414e-08]
 [9.9374324e-01 6.2568113e-03 7.2979991e-09]
 [9.8922753e-01 1.0772477e-02 2.9044909e-08]
 [9.9605525e-01 3.9447378e-03 1.5669180e-09]
 [9.9583769e-01 4.1623567e-03 1.2103436e-09]
 [9.9360400e-01 6.3960687e-03 9.2573433e-09]
 [9.9443263e-01 5.5673341e-03 4.0319343e-09]
 [9.8669541e-01 1.3304429e-02 6.0813143e-08]
 [9.9121422e-01 8.7857749e-03 1.1634132e-08]]
Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'],
      dtype='object')


In [9]:
print(y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [13]:
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
from sklearn.metrics import accuracy_score

correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.98


In [23]:
sample_flower = np.array([[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}.")

[[0.00129934 0.49863774 0.5000629 ]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica.


In [22]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} are: {species[pred]}.")

[[1.2993371e-03 4.9863786e-01 5.0006276e-01]
 [9.8552877e-01 1.4471186e-02 2.0212246e-08]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object').
